#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.DBConexion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Microproyecto_prog")]
	public partial class DBLibraryEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insert_HabitacionXMotel(_HabitacionXMotel instance);
    partial void Update_HabitacionXMotel(_HabitacionXMotel instance);
    partial void Delete_HabitacionXMotel(_HabitacionXMotel instance);
    partial void InsertTipoHabitacion(TipoHabitacion instance);
    partial void UpdateTipoHabitacion(TipoHabitacion instance);
    partial void DeleteTipoHabitacion(TipoHabitacion instance);
    partial void InsertFormas_de_pago(Formas_de_pago instance);
    partial void UpdateFormas_de_pago(Formas_de_pago instance);
    partial void DeleteFormas_de_pago(Formas_de_pago instance);
    partial void InsertLista_Usuarios(Lista_Usuarios instance);
    partial void UpdateLista_Usuarios(Lista_Usuarios instance);
    partial void DeleteLista_Usuarios(Lista_Usuarios instance);
    partial void InsertLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void UpdateLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void DeleteLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void InsertMotel(Motel instance);
    partial void UpdateMotel(Motel instance);
    partial void DeleteMotel(Motel instance);
    partial void InsertMotel_Forma_Pago(Motel_Forma_Pago instance);
    partial void UpdateMotel_Forma_Pago(Motel_Forma_Pago instance);
    partial void DeleteMotel_Forma_Pago(Motel_Forma_Pago instance);
    partial void InsertPuntuaciones(Puntuaciones instance);
    partial void UpdatePuntuaciones(Puntuaciones instance);
    partial void DeletePuntuaciones(Puntuaciones instance);
    partial void InsertSectores(Sectores instance);
    partial void UpdateSectores(Sectores instance);
    partial void DeleteSectores(Sectores instance);
    partial void InsertServicios(Servicios instance);
    partial void UpdateServicios(Servicios instance);
    partial void DeleteServicios(Servicios instance);
    partial void InsertServiciosXhabitaciones(ServiciosXhabitaciones instance);
    partial void UpdateServiciosXhabitaciones(ServiciosXhabitaciones instance);
    partial void DeleteServiciosXhabitaciones(ServiciosXhabitaciones instance);
    #endregion
		
		public DBLibraryEntityDataContext() : 
				base(global::Datos.Properties.Settings.Default.Microproyecto_progConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_HabitacionXMotel> _HabitacionXMotel
		{
			get
			{
				return this.GetTable<_HabitacionXMotel>();
			}
		}
		
		public System.Data.Linq.Table<TipoHabitacion> TipoHabitacion
		{
			get
			{
				return this.GetTable<TipoHabitacion>();
			}
		}
		
		public System.Data.Linq.Table<Formas_de_pago> Formas_de_pago
		{
			get
			{
				return this.GetTable<Formas_de_pago>();
			}
		}
		
		public System.Data.Linq.Table<Lista_Usuarios> Lista_Usuarios
		{
			get
			{
				return this.GetTable<Lista_Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<LogMantenimiento_Tabla> LogMantenimiento_Tabla
		{
			get
			{
				return this.GetTable<LogMantenimiento_Tabla>();
			}
		}
		
		public System.Data.Linq.Table<Motel> Motel
		{
			get
			{
				return this.GetTable<Motel>();
			}
		}
		
		public System.Data.Linq.Table<Motel_Forma_Pago> Motel_Forma_Pago
		{
			get
			{
				return this.GetTable<Motel_Forma_Pago>();
			}
		}
		
		public System.Data.Linq.Table<Puntuaciones> Puntuaciones
		{
			get
			{
				return this.GetTable<Puntuaciones>();
			}
		}
		
		public System.Data.Linq.Table<Sectores> Sectores
		{
			get
			{
				return this.GetTable<Sectores>();
			}
		}
		
		public System.Data.Linq.Table<Servicios> Servicios
		{
			get
			{
				return this.GetTable<Servicios>();
			}
		}
		
		public System.Data.Linq.Table<ServiciosXhabitaciones> ServiciosXhabitaciones
		{
			get
			{
				return this.GetTable<ServiciosXhabitaciones>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_Precios")]
		public ISingleResult<Buscar_PreciosResult> Buscar_Precios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Motel", DbType="Int")] System.Nullable<int> id_Motel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Tipo", DbType="Int")] System.Nullable<int> iD_Tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Motel, iD_Tipo);
			return ((ISingleResult<Buscar_PreciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarPagos")]
		public int GuardarPagos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Motel", DbType="Int")] System.Nullable<int> id_Motel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Pago", DbType="Int")] System.Nullable<int> id_Pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Motel, id_Pago);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditarMantenimiento")]
		public int EditarMantenimiento([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Table", DbType="Int")] System.Nullable<int> id_Table, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="NVarChar(50)")] string estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Table, nombre, descripcion, fecha, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarRegistroPorID")]
		public int EliminarRegistroPorID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Guardar_Habitaciones")]
		public int Guardar_Habitaciones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Int")] System.Nullable<int> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), precio, id, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Guardar_Motel")]
		public int Guardar_Motel([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ubicacion", DbType="NVarChar(MAX)")] string ubicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sector", DbType="Int")] System.Nullable<int> sector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_User", DbType="Int")] System.Nullable<int> id_User)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, ubicacion, sector, id_User);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Guardar_Servicios")]
		public int Guardar_Servicios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Motel", DbType="Int")] System.Nullable<int> motel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Habitaciones", DbType="Int")] System.Nullable<int> habitaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Servicio", DbType="Int")] System.Nullable<int> servicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), motel, habitaciones, servicio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Guardar_Usuario")]
		public int Guardar_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pswd", DbType="NVarChar(50)")] string pswd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_usuario", DbType="NVarChar(50)")] string tipo_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, pswd, tipo_usuario, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Registro")]
		public int Registro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Usuario", DbType="NVarChar(25)")] string nom_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Usuario);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_HabitacionXMotel]")]
	public partial class _HabitacionXMotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_TipoHabXMotel;
		
		private decimal _Precio;
		
		private int _Id_Motel;
		
		private int _Id_TipoHabitaciones;
		
		private EntityRef<TipoHabitacion> _TipoHabitacion;
		
		private EntityRef<Motel> _Motel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TipoHabXMotelChanging(int value);
    partial void OnId_TipoHabXMotelChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnId_MotelChanging(int value);
    partial void OnId_MotelChanged();
    partial void OnId_TipoHabitacionesChanging(int value);
    partial void OnId_TipoHabitacionesChanged();
    #endregion
		
		public _HabitacionXMotel()
		{
			this._TipoHabitacion = default(EntityRef<TipoHabitacion>);
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TipoHabXMotel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_TipoHabXMotel
		{
			get
			{
				return this._Id_TipoHabXMotel;
			}
			set
			{
				if ((this._Id_TipoHabXMotel != value))
				{
					this.OnId_TipoHabXMotelChanging(value);
					this.SendPropertyChanging();
					this._Id_TipoHabXMotel = value;
					this.SendPropertyChanged("Id_TipoHabXMotel");
					this.OnId_TipoHabXMotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Motel", DbType="Int NOT NULL")]
		public int Id_Motel
		{
			get
			{
				return this._Id_Motel;
			}
			set
			{
				if ((this._Id_Motel != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_MotelChanging(value);
					this.SendPropertyChanging();
					this._Id_Motel = value;
					this.SendPropertyChanged("Id_Motel");
					this.OnId_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TipoHabitaciones", DbType="Int NOT NULL")]
		public int Id_TipoHabitaciones
		{
			get
			{
				return this._Id_TipoHabitaciones;
			}
			set
			{
				if ((this._Id_TipoHabitaciones != value))
				{
					if (this._TipoHabitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_TipoHabitacionesChanging(value);
					this.SendPropertyChanging();
					this._Id_TipoHabitaciones = value;
					this.SendPropertyChanged("Id_TipoHabitaciones");
					this.OnId_TipoHabitacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoHabitacion__HabitacionXMotel", Storage="_TipoHabitacion", ThisKey="Id_TipoHabitaciones", OtherKey="Id_TipoHabitaciones", IsForeignKey=true)]
		public TipoHabitacion TipoHabitacion
		{
			get
			{
				return this._TipoHabitacion.Entity;
			}
			set
			{
				TipoHabitacion previousValue = this._TipoHabitacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoHabitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoHabitacion.Entity = null;
						previousValue._HabitacionXMotel.Remove(this);
					}
					this._TipoHabitacion.Entity = value;
					if ((value != null))
					{
						value._HabitacionXMotel.Add(this);
						this._Id_TipoHabitaciones = value.Id_TipoHabitaciones;
					}
					else
					{
						this._Id_TipoHabitaciones = default(int);
					}
					this.SendPropertyChanged("TipoHabitacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel__HabitacionXMotel", Storage="_Motel", ThisKey="Id_Motel", OtherKey="Id_Motel", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue._HabitacionXMotel.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value._HabitacionXMotel.Add(this);
						this._Id_Motel = value.Id_Motel;
					}
					else
					{
						this._Id_Motel = default(int);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoHabitacion")]
	public partial class TipoHabitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_TipoHabitaciones;
		
		private string _Tipo_Habitacion;
		
		private EntitySet<_HabitacionXMotel> @__HabitacionXMotel;
		
		private EntitySet<ServiciosXhabitaciones> _ServiciosXhabitaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TipoHabitacionesChanging(int value);
    partial void OnId_TipoHabitacionesChanged();
    partial void OnTipo_HabitacionChanging(string value);
    partial void OnTipo_HabitacionChanged();
    #endregion
		
		public TipoHabitacion()
		{
			this.@__HabitacionXMotel = new EntitySet<_HabitacionXMotel>(new Action<_HabitacionXMotel>(this.attach__HabitacionXMotel), new Action<_HabitacionXMotel>(this.detach__HabitacionXMotel));
			this._ServiciosXhabitaciones = new EntitySet<ServiciosXhabitaciones>(new Action<ServiciosXhabitaciones>(this.attach_ServiciosXhabitaciones), new Action<ServiciosXhabitaciones>(this.detach_ServiciosXhabitaciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TipoHabitaciones", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_TipoHabitaciones
		{
			get
			{
				return this._Id_TipoHabitaciones;
			}
			set
			{
				if ((this._Id_TipoHabitaciones != value))
				{
					this.OnId_TipoHabitacionesChanging(value);
					this.SendPropertyChanging();
					this._Id_TipoHabitaciones = value;
					this.SendPropertyChanged("Id_TipoHabitaciones");
					this.OnId_TipoHabitacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Habitacion", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Tipo_Habitacion
		{
			get
			{
				return this._Tipo_Habitacion;
			}
			set
			{
				if ((this._Tipo_Habitacion != value))
				{
					this.OnTipo_HabitacionChanging(value);
					this.SendPropertyChanging();
					this._Tipo_Habitacion = value;
					this.SendPropertyChanged("Tipo_Habitacion");
					this.OnTipo_HabitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoHabitacion__HabitacionXMotel", Storage="__HabitacionXMotel", ThisKey="Id_TipoHabitaciones", OtherKey="Id_TipoHabitaciones")]
		public EntitySet<_HabitacionXMotel> _HabitacionXMotel
		{
			get
			{
				return this.@__HabitacionXMotel;
			}
			set
			{
				this.@__HabitacionXMotel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoHabitacion_ServiciosXhabitaciones", Storage="_ServiciosXhabitaciones", ThisKey="Id_TipoHabitaciones", OtherKey="ID_Habitaciones")]
		public EntitySet<ServiciosXhabitaciones> ServiciosXhabitaciones
		{
			get
			{
				return this._ServiciosXhabitaciones;
			}
			set
			{
				this._ServiciosXhabitaciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__HabitacionXMotel(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.TipoHabitacion = this;
		}
		
		private void detach__HabitacionXMotel(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.TipoHabitacion = null;
		}
		
		private void attach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.TipoHabitacion = this;
		}
		
		private void detach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.TipoHabitacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Formas_de_pago")]
	public partial class Formas_de_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_FormadePago;
		
		private string _Forma_pago;
		
		private EntitySet<Motel_Forma_Pago> _Motel_Forma_Pago;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_FormadePagoChanging(int value);
    partial void OnId_FormadePagoChanged();
    partial void OnForma_pagoChanging(string value);
    partial void OnForma_pagoChanged();
    #endregion
		
		public Formas_de_pago()
		{
			this._Motel_Forma_Pago = new EntitySet<Motel_Forma_Pago>(new Action<Motel_Forma_Pago>(this.attach_Motel_Forma_Pago), new Action<Motel_Forma_Pago>(this.detach_Motel_Forma_Pago));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_FormadePago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_FormadePago
		{
			get
			{
				return this._Id_FormadePago;
			}
			set
			{
				if ((this._Id_FormadePago != value))
				{
					this.OnId_FormadePagoChanging(value);
					this.SendPropertyChanging();
					this._Id_FormadePago = value;
					this.SendPropertyChanged("Id_FormadePago");
					this.OnId_FormadePagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forma_pago", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Forma_pago
		{
			get
			{
				return this._Forma_pago;
			}
			set
			{
				if ((this._Forma_pago != value))
				{
					this.OnForma_pagoChanging(value);
					this.SendPropertyChanging();
					this._Forma_pago = value;
					this.SendPropertyChanged("Forma_pago");
					this.OnForma_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formas_de_pago_Motel_Forma_Pago", Storage="_Motel_Forma_Pago", ThisKey="Id_FormadePago", OtherKey="Id_Formas_Pago")]
		public EntitySet<Motel_Forma_Pago> Motel_Forma_Pago
		{
			get
			{
				return this._Motel_Forma_Pago;
			}
			set
			{
				this._Motel_Forma_Pago.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Motel_Forma_Pago(Motel_Forma_Pago entity)
		{
			this.SendPropertyChanging();
			entity.Formas_de_pago = this;
		}
		
		private void detach_Motel_Forma_Pago(Motel_Forma_Pago entity)
		{
			this.SendPropertyChanging();
			entity.Formas_de_pago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lista_Usuarios")]
	public partial class Lista_Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Nom_Usuario;
		
		private string _Psswd;
		
		private string _Tipo_usuario;
		
		private bool _Estatus;
		
		private EntitySet<Motel> _Motel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnNom_UsuarioChanging(string value);
    partial void OnNom_UsuarioChanged();
    partial void OnPsswdChanging(string value);
    partial void OnPsswdChanged();
    partial void OnTipo_usuarioChanging(string value);
    partial void OnTipo_usuarioChanged();
    partial void OnEstatusChanging(bool value);
    partial void OnEstatusChanged();
    #endregion
		
		public Lista_Usuarios()
		{
			this._Motel = new EntitySet<Motel>(new Action<Motel>(this.attach_Motel), new Action<Motel>(this.detach_Motel));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Usuario", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Nom_Usuario
		{
			get
			{
				return this._Nom_Usuario;
			}
			set
			{
				if ((this._Nom_Usuario != value))
				{
					this.OnNom_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Nom_Usuario = value;
					this.SendPropertyChanged("Nom_Usuario");
					this.OnNom_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Psswd", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Psswd
		{
			get
			{
				return this._Psswd;
			}
			set
			{
				if ((this._Psswd != value))
				{
					this.OnPsswdChanging(value);
					this.SendPropertyChanging();
					this._Psswd = value;
					this.SendPropertyChanged("Psswd");
					this.OnPsswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_usuario", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Tipo_usuario
		{
			get
			{
				return this._Tipo_usuario;
			}
			set
			{
				if ((this._Tipo_usuario != value))
				{
					this.OnTipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Tipo_usuario = value;
					this.SendPropertyChanged("Tipo_usuario");
					this.OnTipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lista_Usuarios_Motel", Storage="_Motel", ThisKey="Id_Usuario", OtherKey="ID_Usuario")]
		public EntitySet<Motel> Motel
		{
			get
			{
				return this._Motel;
			}
			set
			{
				this._Motel.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Motel(Motel entity)
		{
			this.SendPropertyChanging();
			entity.Lista_Usuarios = this;
		}
		
		private void detach_Motel(Motel entity)
		{
			this.SendPropertyChanging();
			entity.Lista_Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogMantenimiento_Tabla")]
	public partial class LogMantenimiento_Tabla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Tabla;
		
		private string _Nom_Usuario;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		private string _Estatus;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TablaChanging(int value);
    partial void OnId_TablaChanged();
    partial void OnNom_UsuarioChanging(string value);
    partial void OnNom_UsuarioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnEstatusChanging(string value);
    partial void OnEstatusChanged();
    #endregion
		
		public LogMantenimiento_Tabla()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Tabla", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Tabla
		{
			get
			{
				return this._Id_Tabla;
			}
			set
			{
				if ((this._Id_Tabla != value))
				{
					this.OnId_TablaChanging(value);
					this.SendPropertyChanging();
					this._Id_Tabla = value;
					this.SendPropertyChanged("Id_Tabla");
					this.OnId_TablaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom_Usuario
		{
			get
			{
				return this._Nom_Usuario;
			}
			set
			{
				if ((this._Nom_Usuario != value))
				{
					this.OnNom_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Nom_Usuario = value;
					this.SendPropertyChanged("Nom_Usuario");
					this.OnNom_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Motel")]
	public partial class Motel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Motel;
		
		private string _Nombre;
		
		private string _Ubicacion;
		
		private int _Id_Sector;
		
		private int _ID_Usuario;
		
		private EntitySet<_HabitacionXMotel> @__HabitacionXMotel;
		
		private EntitySet<Motel_Forma_Pago> _Motel_Forma_Pago;
		
		private EntitySet<Puntuaciones> _Puntuaciones;
		
		private EntitySet<ServiciosXhabitaciones> _ServiciosXhabitaciones;
		
		private EntityRef<Lista_Usuarios> _Lista_Usuarios;
		
		private EntityRef<Sectores> _Sectores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_MotelChanging(int value);
    partial void OnId_MotelChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUbicacionChanging(string value);
    partial void OnUbicacionChanged();
    partial void OnId_SectorChanging(int value);
    partial void OnId_SectorChanged();
    partial void OnID_UsuarioChanging(int value);
    partial void OnID_UsuarioChanged();
    #endregion
		
		public Motel()
		{
			this.@__HabitacionXMotel = new EntitySet<_HabitacionXMotel>(new Action<_HabitacionXMotel>(this.attach__HabitacionXMotel), new Action<_HabitacionXMotel>(this.detach__HabitacionXMotel));
			this._Motel_Forma_Pago = new EntitySet<Motel_Forma_Pago>(new Action<Motel_Forma_Pago>(this.attach_Motel_Forma_Pago), new Action<Motel_Forma_Pago>(this.detach_Motel_Forma_Pago));
			this._Puntuaciones = new EntitySet<Puntuaciones>(new Action<Puntuaciones>(this.attach_Puntuaciones), new Action<Puntuaciones>(this.detach_Puntuaciones));
			this._ServiciosXhabitaciones = new EntitySet<ServiciosXhabitaciones>(new Action<ServiciosXhabitaciones>(this.attach_ServiciosXhabitaciones), new Action<ServiciosXhabitaciones>(this.detach_ServiciosXhabitaciones));
			this._Lista_Usuarios = default(EntityRef<Lista_Usuarios>);
			this._Sectores = default(EntityRef<Sectores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Motel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Motel
		{
			get
			{
				return this._Id_Motel;
			}
			set
			{
				if ((this._Id_Motel != value))
				{
					this.OnId_MotelChanging(value);
					this.SendPropertyChanging();
					this._Id_Motel = value;
					this.SendPropertyChanged("Id_Motel");
					this.OnId_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Ubicacion
		{
			get
			{
				return this._Ubicacion;
			}
			set
			{
				if ((this._Ubicacion != value))
				{
					this.OnUbicacionChanging(value);
					this.SendPropertyChanging();
					this._Ubicacion = value;
					this.SendPropertyChanged("Ubicacion");
					this.OnUbicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sector", DbType="Int NOT NULL")]
		public int Id_Sector
		{
			get
			{
				return this._Id_Sector;
			}
			set
			{
				if ((this._Id_Sector != value))
				{
					if (this._Sectores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_SectorChanging(value);
					this.SendPropertyChanging();
					this._Id_Sector = value;
					this.SendPropertyChanged("Id_Sector");
					this.OnId_SectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="Int NOT NULL")]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					if (this._Lista_Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel__HabitacionXMotel", Storage="__HabitacionXMotel", ThisKey="Id_Motel", OtherKey="Id_Motel")]
		public EntitySet<_HabitacionXMotel> _HabitacionXMotel
		{
			get
			{
				return this.@__HabitacionXMotel;
			}
			set
			{
				this.@__HabitacionXMotel.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Motel_Forma_Pago", Storage="_Motel_Forma_Pago", ThisKey="Id_Motel", OtherKey="Id_Motel")]
		public EntitySet<Motel_Forma_Pago> Motel_Forma_Pago
		{
			get
			{
				return this._Motel_Forma_Pago;
			}
			set
			{
				this._Motel_Forma_Pago.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Puntuaciones", Storage="_Puntuaciones", ThisKey="Id_Motel", OtherKey="Id_Motel")]
		public EntitySet<Puntuaciones> Puntuaciones
		{
			get
			{
				return this._Puntuaciones;
			}
			set
			{
				this._Puntuaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_ServiciosXhabitaciones", Storage="_ServiciosXhabitaciones", ThisKey="Id_Motel", OtherKey="ID_Motel")]
		public EntitySet<ServiciosXhabitaciones> ServiciosXhabitaciones
		{
			get
			{
				return this._ServiciosXhabitaciones;
			}
			set
			{
				this._ServiciosXhabitaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lista_Usuarios_Motel", Storage="_Lista_Usuarios", ThisKey="ID_Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public Lista_Usuarios Lista_Usuarios
		{
			get
			{
				return this._Lista_Usuarios.Entity;
			}
			set
			{
				Lista_Usuarios previousValue = this._Lista_Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Lista_Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lista_Usuarios.Entity = null;
						previousValue.Motel.Remove(this);
					}
					this._Lista_Usuarios.Entity = value;
					if ((value != null))
					{
						value.Motel.Add(this);
						this._ID_Usuario = value.Id_Usuario;
					}
					else
					{
						this._ID_Usuario = default(int);
					}
					this.SendPropertyChanged("Lista_Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sectores_Motel", Storage="_Sectores", ThisKey="Id_Sector", OtherKey="Id_Sector", IsForeignKey=true)]
		public Sectores Sectores
		{
			get
			{
				return this._Sectores.Entity;
			}
			set
			{
				Sectores previousValue = this._Sectores.Entity;
				if (((previousValue != value) 
							|| (this._Sectores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sectores.Entity = null;
						previousValue.Motel.Remove(this);
					}
					this._Sectores.Entity = value;
					if ((value != null))
					{
						value.Motel.Add(this);
						this._Id_Sector = value.Id_Sector;
					}
					else
					{
						this._Id_Sector = default(int);
					}
					this.SendPropertyChanged("Sectores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__HabitacionXMotel(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach__HabitacionXMotel(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
		
		private void attach_Motel_Forma_Pago(Motel_Forma_Pago entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_Motel_Forma_Pago(Motel_Forma_Pago entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
		
		private void attach_Puntuaciones(Puntuaciones entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_Puntuaciones(Puntuaciones entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
		
		private void attach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.Motel = this;
		}
		
		private void detach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.Motel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Motel_Forma_Pago")]
	public partial class Motel_Forma_Pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Motel_forma_pago;
		
		private int _Id_Motel;
		
		private int _Id_Formas_Pago;
		
		private EntityRef<Motel> _Motel;
		
		private EntityRef<Formas_de_pago> _Formas_de_pago;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Motel_forma_pagoChanging(int value);
    partial void OnId_Motel_forma_pagoChanged();
    partial void OnId_MotelChanging(int value);
    partial void OnId_MotelChanged();
    partial void OnId_Formas_PagoChanging(int value);
    partial void OnId_Formas_PagoChanged();
    #endregion
		
		public Motel_Forma_Pago()
		{
			this._Motel = default(EntityRef<Motel>);
			this._Formas_de_pago = default(EntityRef<Formas_de_pago>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Motel_forma_pago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Motel_forma_pago
		{
			get
			{
				return this._Id_Motel_forma_pago;
			}
			set
			{
				if ((this._Id_Motel_forma_pago != value))
				{
					this.OnId_Motel_forma_pagoChanging(value);
					this.SendPropertyChanging();
					this._Id_Motel_forma_pago = value;
					this.SendPropertyChanged("Id_Motel_forma_pago");
					this.OnId_Motel_forma_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Motel", DbType="Int NOT NULL")]
		public int Id_Motel
		{
			get
			{
				return this._Id_Motel;
			}
			set
			{
				if ((this._Id_Motel != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_MotelChanging(value);
					this.SendPropertyChanging();
					this._Id_Motel = value;
					this.SendPropertyChanged("Id_Motel");
					this.OnId_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Formas_Pago", DbType="Int NOT NULL")]
		public int Id_Formas_Pago
		{
			get
			{
				return this._Id_Formas_Pago;
			}
			set
			{
				if ((this._Id_Formas_Pago != value))
				{
					if (this._Formas_de_pago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_Formas_PagoChanging(value);
					this.SendPropertyChanging();
					this._Id_Formas_Pago = value;
					this.SendPropertyChanged("Id_Formas_Pago");
					this.OnId_Formas_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Motel_Forma_Pago", Storage="_Motel", ThisKey="Id_Motel", OtherKey="Id_Motel", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.Motel_Forma_Pago.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.Motel_Forma_Pago.Add(this);
						this._Id_Motel = value.Id_Motel;
					}
					else
					{
						this._Id_Motel = default(int);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formas_de_pago_Motel_Forma_Pago", Storage="_Formas_de_pago", ThisKey="Id_Formas_Pago", OtherKey="Id_FormadePago", IsForeignKey=true)]
		public Formas_de_pago Formas_de_pago
		{
			get
			{
				return this._Formas_de_pago.Entity;
			}
			set
			{
				Formas_de_pago previousValue = this._Formas_de_pago.Entity;
				if (((previousValue != value) 
							|| (this._Formas_de_pago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Formas_de_pago.Entity = null;
						previousValue.Motel_Forma_Pago.Remove(this);
					}
					this._Formas_de_pago.Entity = value;
					if ((value != null))
					{
						value.Motel_Forma_Pago.Add(this);
						this._Id_Formas_Pago = value.Id_FormadePago;
					}
					else
					{
						this._Id_Formas_Pago = default(int);
					}
					this.SendPropertyChanged("Formas_de_pago");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puntuaciones")]
	public partial class Puntuaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Puntuacion;
		
		private System.DateTime _Fecha;
		
		private int _Valoracion;
		
		private string _Resena;
		
		private int _Id_Motel;
		
		private EntityRef<Motel> _Motel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PuntuacionChanging(int value);
    partial void OnId_PuntuacionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnValoracionChanging(int value);
    partial void OnValoracionChanged();
    partial void OnResenaChanging(string value);
    partial void OnResenaChanged();
    partial void OnId_MotelChanging(int value);
    partial void OnId_MotelChanged();
    #endregion
		
		public Puntuaciones()
		{
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Puntuacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Puntuacion
		{
			get
			{
				return this._Id_Puntuacion;
			}
			set
			{
				if ((this._Id_Puntuacion != value))
				{
					this.OnId_PuntuacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Puntuacion = value;
					this.SendPropertyChanged("Id_Puntuacion");
					this.OnId_PuntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valoracion", DbType="Int NOT NULL")]
		public int Valoracion
		{
			get
			{
				return this._Valoracion;
			}
			set
			{
				if ((this._Valoracion != value))
				{
					this.OnValoracionChanging(value);
					this.SendPropertyChanging();
					this._Valoracion = value;
					this.SendPropertyChanged("Valoracion");
					this.OnValoracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resena", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Resena
		{
			get
			{
				return this._Resena;
			}
			set
			{
				if ((this._Resena != value))
				{
					this.OnResenaChanging(value);
					this.SendPropertyChanging();
					this._Resena = value;
					this.SendPropertyChanged("Resena");
					this.OnResenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Motel", DbType="Int NOT NULL")]
		public int Id_Motel
		{
			get
			{
				return this._Id_Motel;
			}
			set
			{
				if ((this._Id_Motel != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_MotelChanging(value);
					this.SendPropertyChanging();
					this._Id_Motel = value;
					this.SendPropertyChanged("Id_Motel");
					this.OnId_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_Puntuaciones", Storage="_Motel", ThisKey="Id_Motel", OtherKey="Id_Motel", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.Puntuaciones.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.Puntuaciones.Add(this);
						this._Id_Motel = value.Id_Motel;
					}
					else
					{
						this._Id_Motel = default(int);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sectores")]
	public partial class Sectores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Sector;
		
		private string _Sector;
		
		private EntitySet<Motel> _Motel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SectorChanging(int value);
    partial void OnId_SectorChanged();
    partial void OnSectorChanging(string value);
    partial void OnSectorChanged();
    #endregion
		
		public Sectores()
		{
			this._Motel = new EntitySet<Motel>(new Action<Motel>(this.attach_Motel), new Action<Motel>(this.detach_Motel));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Sector", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Sector
		{
			get
			{
				return this._Id_Sector;
			}
			set
			{
				if ((this._Id_Sector != value))
				{
					this.OnId_SectorChanging(value);
					this.SendPropertyChanging();
					this._Id_Sector = value;
					this.SendPropertyChanged("Id_Sector");
					this.OnId_SectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sectores_Motel", Storage="_Motel", ThisKey="Id_Sector", OtherKey="Id_Sector")]
		public EntitySet<Motel> Motel
		{
			get
			{
				return this._Motel;
			}
			set
			{
				this._Motel.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Motel(Motel entity)
		{
			this.SendPropertyChanging();
			entity.Sectores = this;
		}
		
		private void detach_Motel(Motel entity)
		{
			this.SendPropertyChanging();
			entity.Sectores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicios")]
	public partial class Servicios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Servicios;
		
		private string _Servicio;
		
		private EntitySet<ServiciosXhabitaciones> _ServiciosXhabitaciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ServiciosChanging(int value);
    partial void OnID_ServiciosChanged();
    partial void OnServicioChanging(string value);
    partial void OnServicioChanged();
    #endregion
		
		public Servicios()
		{
			this._ServiciosXhabitaciones = new EntitySet<ServiciosXhabitaciones>(new Action<ServiciosXhabitaciones>(this.attach_ServiciosXhabitaciones), new Action<ServiciosXhabitaciones>(this.detach_ServiciosXhabitaciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Servicios", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Servicios
		{
			get
			{
				return this._ID_Servicios;
			}
			set
			{
				if ((this._ID_Servicios != value))
				{
					this.OnID_ServiciosChanging(value);
					this.SendPropertyChanging();
					this._ID_Servicios = value;
					this.SendPropertyChanged("ID_Servicios");
					this.OnID_ServiciosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Servicio
		{
			get
			{
				return this._Servicio;
			}
			set
			{
				if ((this._Servicio != value))
				{
					this.OnServicioChanging(value);
					this.SendPropertyChanging();
					this._Servicio = value;
					this.SendPropertyChanged("Servicio");
					this.OnServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicios_ServiciosXhabitaciones", Storage="_ServiciosXhabitaciones", ThisKey="ID_Servicios", OtherKey="ID_Servicio")]
		public EntitySet<ServiciosXhabitaciones> ServiciosXhabitaciones
		{
			get
			{
				return this._ServiciosXhabitaciones;
			}
			set
			{
				this._ServiciosXhabitaciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.Servicios = this;
		}
		
		private void detach_ServiciosXhabitaciones(ServiciosXhabitaciones entity)
		{
			this.SendPropertyChanging();
			entity.Servicios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServiciosXhabitaciones")]
	public partial class ServiciosXhabitaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ServiciosXhabitaciones;
		
		private int _ID_Motel;
		
		private int _ID_Habitaciones;
		
		private int _ID_Servicio;
		
		private EntityRef<Servicios> _Servicios;
		
		private EntityRef<TipoHabitacion> _TipoHabitacion;
		
		private EntityRef<Motel> _Motel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ServiciosXhabitacionesChanging(int value);
    partial void OnID_ServiciosXhabitacionesChanged();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    partial void OnID_HabitacionesChanging(int value);
    partial void OnID_HabitacionesChanged();
    partial void OnID_ServicioChanging(int value);
    partial void OnID_ServicioChanged();
    #endregion
		
		public ServiciosXhabitaciones()
		{
			this._Servicios = default(EntityRef<Servicios>);
			this._TipoHabitacion = default(EntityRef<TipoHabitacion>);
			this._Motel = default(EntityRef<Motel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ServiciosXhabitaciones", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ServiciosXhabitaciones
		{
			get
			{
				return this._ID_ServiciosXhabitaciones;
			}
			set
			{
				if ((this._ID_ServiciosXhabitaciones != value))
				{
					this.OnID_ServiciosXhabitacionesChanging(value);
					this.SendPropertyChanging();
					this._ID_ServiciosXhabitaciones = value;
					this.SendPropertyChanged("ID_ServiciosXhabitaciones");
					this.OnID_ServiciosXhabitacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", DbType="Int NOT NULL")]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					if (this._Motel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Habitaciones", DbType="Int NOT NULL")]
		public int ID_Habitaciones
		{
			get
			{
				return this._ID_Habitaciones;
			}
			set
			{
				if ((this._ID_Habitaciones != value))
				{
					if (this._TipoHabitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HabitacionesChanging(value);
					this.SendPropertyChanging();
					this._ID_Habitaciones = value;
					this.SendPropertyChanged("ID_Habitaciones");
					this.OnID_HabitacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Servicio", DbType="Int NOT NULL")]
		public int ID_Servicio
		{
			get
			{
				return this._ID_Servicio;
			}
			set
			{
				if ((this._ID_Servicio != value))
				{
					if (this._Servicios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ServicioChanging(value);
					this.SendPropertyChanging();
					this._ID_Servicio = value;
					this.SendPropertyChanged("ID_Servicio");
					this.OnID_ServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicios_ServiciosXhabitaciones", Storage="_Servicios", ThisKey="ID_Servicio", OtherKey="ID_Servicios", IsForeignKey=true)]
		public Servicios Servicios
		{
			get
			{
				return this._Servicios.Entity;
			}
			set
			{
				Servicios previousValue = this._Servicios.Entity;
				if (((previousValue != value) 
							|| (this._Servicios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicios.Entity = null;
						previousValue.ServiciosXhabitaciones.Remove(this);
					}
					this._Servicios.Entity = value;
					if ((value != null))
					{
						value.ServiciosXhabitaciones.Add(this);
						this._ID_Servicio = value.ID_Servicios;
					}
					else
					{
						this._ID_Servicio = default(int);
					}
					this.SendPropertyChanged("Servicios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoHabitacion_ServiciosXhabitaciones", Storage="_TipoHabitacion", ThisKey="ID_Habitaciones", OtherKey="Id_TipoHabitaciones", IsForeignKey=true)]
		public TipoHabitacion TipoHabitacion
		{
			get
			{
				return this._TipoHabitacion.Entity;
			}
			set
			{
				TipoHabitacion previousValue = this._TipoHabitacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoHabitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoHabitacion.Entity = null;
						previousValue.ServiciosXhabitaciones.Remove(this);
					}
					this._TipoHabitacion.Entity = value;
					if ((value != null))
					{
						value.ServiciosXhabitaciones.Add(this);
						this._ID_Habitaciones = value.Id_TipoHabitaciones;
					}
					else
					{
						this._ID_Habitaciones = default(int);
					}
					this.SendPropertyChanged("TipoHabitacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motel_ServiciosXhabitaciones", Storage="_Motel", ThisKey="ID_Motel", OtherKey="Id_Motel", IsForeignKey=true)]
		public Motel Motel
		{
			get
			{
				return this._Motel.Entity;
			}
			set
			{
				Motel previousValue = this._Motel.Entity;
				if (((previousValue != value) 
							|| (this._Motel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motel.Entity = null;
						previousValue.ServiciosXhabitaciones.Remove(this);
					}
					this._Motel.Entity = value;
					if ((value != null))
					{
						value.ServiciosXhabitaciones.Add(this);
						this._ID_Motel = value.Id_Motel;
					}
					else
					{
						this._ID_Motel = default(int);
					}
					this.SendPropertyChanged("Motel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Buscar_PreciosResult
	{
		
		private decimal _Precio;
		
		public Buscar_PreciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
